"""Canonical language metadata shared by config, prompts and model contracts.

Sources reviewed 2026-10-05 UTC: official Qwen3-ASR-0.6B, NVIDIA Parakeet
TDT v3 and Tencent Hy-MT2-1.8B model cards. Keep codes here, not in UI.
Hy-MT2's explicit table takes precedence over its older "33 languages" headline.
Cloud/custom endpoints retain their existing declared contract; not inferred.
"""
from __future__ import annotations

LANGUAGE_NAMES = {'zh': 'Chinese',
 'en': 'English',
 'ja': 'Japanese',
 'ko': 'Korean',
 'fr': 'French',
 'pt': 'Portuguese',
 'es': 'Spanish',
 'tr': 'Turkish',
 'ru': 'Russian',
 'ar': 'Arabic',
 'th': 'Thai',
 'it': 'Italian',
 'de': 'German',
 'vi': 'Vietnamese',
 'ms': 'Malay',
 'id': 'Indonesian',
 'fil': 'Filipino',
 'hi': 'Hindi',
 'zh-hant': 'Traditional Chinese',
 'pl': 'Polish',
 'cs': 'Czech',
 'nl': 'Dutch',
 'km': 'Khmer',
 'my': 'Burmese',
 'fa': 'Persian',
 'gu': 'Gujarati',
 'ur': 'Urdu',
 'te': 'Telugu',
 'mr': 'Marathi',
 'he': 'Hebrew',
 'bn': 'Bengali',
 'ta': 'Tamil',
 'uk': 'Ukrainian',
 'bo': 'Tibetan',
 'kk': 'Kazakh',
 'mn': 'Mongolian',
 'ug': 'Uyghur',
 'yue': 'Cantonese',
 'sv': 'Swedish',
 'da': 'Danish',
 'fi': 'Finnish',
 'el': 'Greek',
 'hu': 'Hungarian',
 'mk': 'Macedonian',
 'bg': 'Bulgarian',
 'hr': 'Croatian',
 'et': 'Estonian',
 'lt': 'Lithuanian',
 'lv': 'Latvian',
 'mt': 'Maltese',
 'sk': 'Slovak',
 'sl': 'Slovenian',
 'ro': 'Romanian',
 'auto': 'the detected source language'}
LANGUAGE_LABELS = {'zh': '中文',
 'en': '英语',
 'ja': '日语',
 'ko': '韩语',
 'fr': '法语',
 'pt': '葡萄牙语',
 'es': '西班牙语',
 'tr': '土耳其语',
 'ru': '俄语',
 'ar': '阿拉伯语',
 'th': '泰语',
 'it': '意大利语',
 'de': '德语',
 'vi': '越南语',
 'ms': '马来语',
 'id': '印尼语',
 'fil': '菲律宾语',
 'hi': '印地语',
 'zh-hant': '繁体中文',
 'pl': '波兰语',
 'cs': '捷克语',
 'nl': '荷兰语',
 'km': '高棉语',
 'my': '缅甸语',
 'fa': '波斯语',
 'gu': '古吉拉特语',
 'ur': '乌尔都语',
 'te': '泰卢固语',
 'mr': '马拉地语',
 'he': '希伯来语',
 'bn': '孟加拉语',
 'ta': '泰米尔语',
 'uk': '乌克兰语',
 'bo': '藏语',
 'kk': '哈萨克语',
 'mn': '蒙古语',
 'ug': '维吾尔语',
 'yue': '粤语',
 'sv': '瑞典语',
 'da': '丹麦语',
 'fi': '芬兰语',
 'el': '希腊语',
 'hu': '匈牙利语',
 'mk': '马其顿语',
 'bg': '保加利亚语',
 'hr': '克罗地亚语',
 'et': '爱沙尼亚语',
 'lt': '立陶宛语',
 'lv': '拉脱维亚语',
 'mt': '马耳他语',
 'sk': '斯洛伐克语',
 'sl': '斯洛文尼亚语',
 'ro': '罗马尼亚语',
 'auto': '自动识别'}
QWEN_ASR_LANGUAGES = ('zh',
 'en',
 'yue',
 'ar',
 'de',
 'fr',
 'es',
 'pt',
 'id',
 'it',
 'ko',
 'ru',
 'th',
 'vi',
 'ja',
 'tr',
 'hi',
 'ms',
 'nl',
 'sv',
 'da',
 'fi',
 'pl',
 'cs',
 'fil',
 'fa',
 'el',
 'hu',
 'mk',
 'ro')
HY_MT_LANGUAGES = ('zh',
 'en',
 'fr',
 'pt',
 'es',
 'ja',
 'tr',
 'ru',
 'ar',
 'ko',
 'th',
 'it',
 'de',
 'vi',
 'ms',
 'id',
 'fil',
 'hi',
 'zh-hant',
 'pl',
 'cs',
 'nl',
 'km',
 'my',
 'fa',
 'gu',
 'ur',
 'te',
 'mr',
 'he',
 'bn',
 'ta',
 'uk',
 'bo',
 'kk',
 'mn',
 'ug',
 'yue')
PARAKEET_LANGUAGES = tuple("bg hr cs da nl en et fi fr de el hu it lv lt mt pl pt ro ru sk sl es sv uk".split())

ASR_LANGUAGES = {
    "sherpa-streaming-transducer": ("zh", "en"),
    "sherpa-funasr-nano": ("zh", "en", "ja"),
    "sherpa-qwen3-asr": QWEN_ASR_LANGUAGES,
    "sherpa-sense-voice": ("zh", "en", "ja", "ko", "yue"),
    "sherpa-moonshine-v2": ("en",),
    "sherpa-parakeet-tdt": PARAKEET_LANGUAGES,
}
# These adapters cannot change the decoder language without loading again.
LOAD_TIME_LANGUAGE_RUNTIMES = frozenset({"sherpa-funasr-nano"})
LANGUAGE_HINT_MODES = {
    "sherpa-streaming-transducer": "unavailable",
    "sherpa-funasr-nano": "load_time",
    "sherpa-qwen3-asr": "per_stream",
    "sherpa-sense-voice": "decode_config",
    "sherpa-moonshine-v2": "monolingual",
    "sherpa-parakeet-tdt": "unavailable",
}
LANGUAGE_PAIRS = {f"{src}-{dst}": (src, dst)
                  for src in LANGUAGE_NAMES for dst in LANGUAGE_NAMES if dst != "auto"}


def split_language_pair(value: object) -> tuple[str, str]:
    """Parse canonical codes including hyphenated script variants, or reject."""
    key = str(value).strip().lower()
    if key not in LANGUAGE_PAIRS:
        raise ValueError("Unsupported language pair")
    return LANGUAGE_PAIRS[key]
